# Welcome

In [2]:
import numpy as np

In [2]:
myarr = np.array([ 3, 6, 9 ,12])

myarr

array([ 3,  6,  9, 12])

In [3]:
myarr = np.array([ 3, 6, 9 ,12], np.int8)

myarr

array([ 3,  6,  9, 12], dtype=int8)

In [4]:
myarr[0]

3

In [5]:
myarr1 = np.array([[2,4,6,8]])

In [6]:
myarr1[0,1]

4

In [7]:
myarr1.shape

(1, 4)

In [8]:
myarr1.dtype

dtype('int64')

In [9]:
myarr1[0, 2]=44

In [10]:
myarr1

array([[ 2,  4, 44,  8]])

# Array creation: Conversion from other Python structure

In [11]:
listarray = np.array([[1,2,3], [5,8,9], [0,3,1]])

In [12]:
listarray

array([[1, 2, 3],
       [5, 8, 9],
       [0, 3, 1]])

In [13]:
listarray.dtype

dtype('int64')

In [14]:
listarray.shape

(3, 3)

In [15]:
listarray.size

9

In [16]:
np.array({34,23,82})

array({34, 82, 23}, dtype=object)

In [17]:
zeros = np.zeros((2,5))

In [18]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
rng = np.arange(15)

In [20]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
lspace = np.linspace(0,100,5)

In [22]:
lspace

array([  0.,  25.,  50.,  75., 100.])

In [23]:
emp = np.empty((4,6))

In [24]:
emp

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [25]:
emp_like = np.empty_like(lspace)

In [26]:
emp_like

array([  0.,  25.,  50.,  75., 100.])

In [27]:
ide = np.identity(4)

In [28]:
ide

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
ide.shape

(4, 4)

In [30]:
ide.reshape(8, 2)

array([[1., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 1.]])

In [31]:
listarray = listarray.ravel()

In [32]:
listarray

array([1, 2, 3, 5, 8, 9, 0, 3, 1])

In [33]:
listarray.shape

(9,)

In [34]:
x = [[1,2,3],[4,5,6],[7,8,0]]

In [35]:
ar = np.array(x)

In [36]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])

In [37]:
ar.sum(axis=0)

array([12, 15,  9])

In [38]:
ar.sum(axis=1)

array([ 6, 15, 15])

In [39]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 0]])

In [40]:
ar.flat

In [41]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
0


In [42]:
ar.ndim

2

In [43]:
ar.size

9

In [44]:
ar.nbytes

72

In [45]:
one = np.array([[1,81,5],[121, 3, 49]])

In [46]:
one.argmax()

3

In [47]:
one.argmin()

0

In [48]:
one.argsort()

array([[0, 2, 1],
       [1, 2, 0]])

In [49]:
one.argmin(axis=0)

array([0, 1, 0])

In [50]:
one.argmin(axis=1)

array([0, 1])

In [51]:
one.argmax(axis=0)

array([1, 0, 1])

In [52]:
one.argmax(axis=1)

array([1, 0])

In [53]:
one.argsort(axis=0)

array([[0, 1, 0],
       [1, 0, 1]])

In [54]:
one.argsort(axis=1)

array([[0, 2, 1],
       [1, 2, 0]])

In [55]:
lcube = (0, 1, 8, 27 ,64, 125, 236, 483)

In [56]:
acube = np.array(lcube)

In [57]:
acube

array([  0,   1,   8,  27,  64, 125, 236, 483])

In [58]:
acube.reshape((2,2,2))

array([[[  0,   1],
        [  8,  27]],

       [[ 64, 125],
        [236, 483]]])

In [59]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])

In [60]:
ar2 = np.array([[2,3,4],[5,6,7],[8,9,10]])

In [61]:
ar + ar2

array([[ 3,  5,  7],
       [ 9, 11, 13],
       [15, 17, 10]])

In [62]:
[75, 57] + [54, 34]

[75, 57, 54, 34]

In [63]:
ar * ar2

array([[ 2,  6, 12],
       [20, 30, 42],
       [56, 72,  0]])

In [64]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 0.        ]])

In [65]:
ar.sum()

36

In [66]:
np.where(ar>5)

(array([1, 2, 2]), array([2, 0, 1]))

In [67]:
type(np.where(ar<5))

tuple

In [68]:
np.count_nonzero(ar)

8

In [69]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [70]:
import sys

In [71]:
py_ar = [0,4,55,2]

In [72]:
np_ar = np.array(py_ar)

In [73]:
sys.getsizeof(1) * len(py_ar)

112

In [74]:
np_ar.itemsize * np_ar.size

32